name: Python Application Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12.1]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt # Adjust if you have a requirements file
        python -m pip install flake8 pytest # Install flake8 and pytest

    - name: Lint with flake8
      run: |
        # Lint Flask application files
        flake8 app.py
        # Lint tkinter script file
        flake8 tkinter_script.py

    - name: Test with pytest
      run: |
        pytest
